version: '3'

services:
  mysql:
    container_name: tlea_geonneo
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "tlea"
      MYSQL_PASSWORD: "tlea"
      MYSQL_DATABASE: "tlea_geonneo"
    ports:
      - "3307:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"